### ISSUE TITLE
多任务头验证

### ISSUE THREAD

**Issue by guo-pu** [haomo-ai/SuperFusion#11]
你好，感谢提供的论文思路和开源代码
请问有尝试过在SuperFusion的BEV特征后面，接多个任务头吗？比如：3D检测、轨迹预测

**Comment by donghao51** [comment]
你好，我们没有实验接多个任务头，理论上学到一个好的BEV表征之后别的任务也可以泛化

**Comment by guo-pu** [comment]
好的
