### ISSUE TITLE
多GPU训练

### ISSUE THREAD

**Issue by guo-pu** [haomo-ai/SuperFusion#12]
你好，在模型训练中，默认的批量大小（batch size）是4，使用1张A100-40G刚好；
想着把batch size设置为16，使用4张A100-40G训练，但是当前代码中好像不支持多卡训练的是吗？

**Comment by donghao51** [comment]
你好，是的，目前暂时不支持多GPU

**Comment by guo-pu** [comment]
好的，请问后面有计划更新代码，实现多GPU训练吗

**Comment by donghao51** [comment]
你好，目前还没有计划更新

**Comment by guo-pu** [comment]
好的
