### ISSUE TITLE
[param incompatible] eval_iou_split.py

### ISSUE THREAD

**Issue by Lewis-Lu** [haomo-ai/SuperFusion#2]
Hi there, 

while using the code in main branch, the parameter incompatibility occurs. I suppose following params cannot be accepted by the get_model function: (while this pass into the arg through eval __main__ function)

  lidar_pred=args.lidar_pred, 
  use_cross=args.use_cross, 
  add_fuser=args.add_fuser, 
  add_fuser_AlignFA=args.add_fuser_AlignFA, 
  add_fuser_AlignFAnew=args.add_fuser_AlignFAnew,
  add_fuser2=args.add_fuser2

you may fix this,

Thanks, 
Lewis

**Comment by donghao51** [comment]
Thanks for your feedback! I have updated the file.
