### ISSUE TITLE
eval error

### ISSUE THREAD

**Issue by colahe** [haomo-ai/SuperFusion#4]
Hi, first of all your work is great but I have a question, when i evaluate the CD value, i got this error? How can i solve it?
![Screenshot from 2023-09-04 00-05-26](https://github.com/haomo-ai/SuperFusion/assets/90144891/0bbf13c5-13bb-4c52-9393-48f1a918e1b3)

**Comment by donghao51** [comment]
hello, now it should be fine. Thanks for pointing it out

**Comment by colahe** [comment]
> hello, now it should be fine. Thanks for pointing it out

HI, thanks for your reply, now i successfully export the output.json, but when i run  last code (python evaluate_json_split.py --result_path output.json .........), i got a error, do u have some suggestions? Thanks!!!!
![Screenshot from 2023-09-04 15-29-04](https://github.com/haomo-ai/SuperFusion/assets/90144891/b634e91d-7105-48b0-b72f-0d0b067d120a)

**Comment by donghao51** [comment]
hello, could you please try `pip install shapely==1.8.1`

**Comment by colahe** [comment]
> hello, could you please try `pip install shapely==1.8.1`
Hey, That solved my problem, thanks a lot! 🎉

**Comment by donghao51** [comment]
great!
