### ISSUE TITLE
output qualitative HD map prediction results

### ISSUE THREAD

**Issue by colahe** [haomo-ai/SuperFusion#6]
Hi, first of all thank you so much for your work! I have a question, how can i use your model to output the qualitative HD map prediction results? Looking forward to your reply!

**Comment by donghao51** [comment]
hello, you can do this by running `python vis_prediction.py --modelf runs/model.pt --instance_seg --direction_pred --depth_sup --pretrained --add_depth_channel --version v1.0-trainval --dataroot /path/to/nuScenes/`

**Comment by colahe** [comment]
Hi, thanks for your reply, wenn i run this code, i got this error, do u have some good advice?
![Screenshot from 2023-09-11 11-51-15](https://github.com/haomo-ai/SuperFusion/assets/90144891/7aa3f6b2-7c32-4dea-9fdf-8887427bd98e)

**Comment by donghao51** [comment]
hello, now it should be ok. please update the code and check it again

**Comment by colahe** [comment]
hi, it works well now, but i have a question, how can i get the ground truth pic? and can i use nuscenes-test datasets to test the model? because i see only mini and  trainval in choices!

**Comment by donghao51** [comment]
hello, you can get the ground truth by running `python vis_prediction_gt.py --instance_seg --direction_pred --dataroot /path/to/nuScenes/`. 
You should be able to use nuscenes-test datasets to test the model. But we only try on trainval split following HDMapNet.

**Comment by colahe** [comment]
hi, i really appreciate your patient reply! i will have a try on test data, thanks!!!

**Comment by colahe** [comment]
> hello, maybe you can consider doing some modifications here
> 
> https://github.com/haomo-ai/SuperFusion/blob/74d89b0e8f25789d1b4cd55af67af75bf1c068d9/data/dataset_front.py#L49

Ok, i will have a try, ty!!!!
